baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "mike's website"
theme = 'nostyle'

[params]
description = 'writing, mostly about technology'

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3


[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4

[menu.main.post_list]
section = "blog"
limit = 5
show_more = true
show_more_url = "/blog/all"
show_more_text = "View All Posts"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
